### ISSUE TITLE
读取文件报错

### ISSUE THREAD

**Issue by woochanglin** [wangguanquan/eec#145]
读取excel解析numFmt报错，List下标为负

excel文件链接：
http://cloudseek.oss-cn-shanghai.aliyuncs.com/helpFile/麻辣烫.xlsx

错误堆栈：
java.lang.ArrayIndexOutOfBoundsException: -127
	at java.util.ArrayList.elementData(ArrayList.java:422) ~[na:1.8.0_241]
	at java.util.ArrayList.get(ArrayList.java:435) ~[na:1.8.0_241]
	at org.ttzero.excel.entity.style.Styles.findFmtById(Styles.java:801) ~[eec-0.4.8.jar:na]
	at org.ttzero.excel.entity.style.Styles.isDate(Styles.java:647) ~[eec-0.4.8.jar:na]
	at org.ttzero.excel.entity.style.Styles.load(Styles.java:265) ~[eec-0.4.8.jar:na]
	at org.ttzero.excel.reader.ExcelReader.<init>(ExcelReader.java:498) ~[eec-0.4.8.jar:na]
	at org.ttzero.excel.reader.ExcelReader.read(ExcelReader.java:573) ~[eec-0.4.8.jar:na]
	at org.ttzero.excel.reader.ExcelReader.read(ExcelReader.java:242) ~[eec-0.4.8.jar:na]
	at org.ttzero.excel.reader.ExcelReader.read(ExcelReader.java:155) ~[eec-0.4.8.jar:na]

**Comment by wangguanquan** [comment]
感谢你对问题的反馈，一个好项目离不开大家的群策群力，如果你有解决此问题的方案**欢迎提交PR(Pull Request)**，

交接PR步骤
1.  Fork本工程
2. clone你本人fork好的工程   `git clone https://github.com/woochanglin/eec`
3. 创建分支，分支名以fix#issue编号，例：本issue编号为145，使用命令   `git checkout -b fix#145` 新建并切换分支到fix#145
4. 修改代码和注释并为修改部分添加junit测试代码
5. 提交分支并推Pull Request等待合并，如果验证通过后会将你贡献的代码合并到主分支。

**Comment by woochanglin** [comment]
好的，我改个版本提交。
非常好的项目，感谢您的分离。

**Comment by wangguanquan** [comment]
有任何需要帮助的地方请在此留言

**Comment by woochanglin** [comment]
非常感谢

**Comment by wangguanquan** [comment]
v0.4.9 已推，可以升级到该版本以解决此问题，xls格式同样修复了此问题，版本相同。
