### ISSUE TITLE
读取 xls文件时 提示 " Read excel failed" 

### ISSUE THREAD

**Issue by bob798** [wangguanquan/eec#147]
xls文件通过excel另存为生成
excel具体版本号
![image](https://user-images.githubusercontent.com/22414400/102477973-02233300-4098-11eb-9749-b4628a88f257.png)
尝试多次无法读取xls文件，望帮忙看下。
具体错误信息：
Exception in thread "main" org.ttzero.excel.reader.ExcelReadException: Read excel failed.
	at org.ttzero.excel.reader.ExcelReader.read(ExcelReader.java:591)
	at org.ttzero.excel.reader.ExcelReader.read(ExcelReader.java:222)
	at org.ttzero.excel.reader.ExcelReader.read(ExcelReader.java:144)
	at excel.excelWriteAndRead.read(excelWriteAndRead.java:61)
	at excel.excelWriteAndRead.main(excelWriteAndRead.java:97)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.ttzero.excel.reader.ExcelReader.read(ExcelReader.java:579)
	... 4 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: arraycopy: source index -1 out of bounds for object array[16]
	at java.base/java.lang.System.arraycopy(Native Method)
	at org.ttzero.excel.entity.e3.oleps.WindowsVersionEnum.get(WindowsVersionEnum.java:61)
	at org.ttzero.excel.entity.e3.oleps.PropertySetStreamParser.get(PropertySetStreamParser.java:59)
	at org.ttzero.excel.reader.BIFF8Reader.parseDocSummaryInformation(BIFF8Reader.java:475)
	at org.ttzero.excel.reader.BIFF8Reader.init(BIFF8Reader.java:140)
	at org.ttzero.excel.reader.BIFF8Reader.<init>(BIFF8Reader.java:90)
	... 10 more

测试代码：
  public static void main(String[] args) throws IOException {
    readXls("/Users/test/Desktop/testxls.xls");

  }
  public static void readXls(String path) {
    try (ExcelReader reader = ExcelReader.read(Paths.get(path))) {
      reader.sheets().flatMap(Sheet::rows).forEach(System.out::println);
    } catch (IOException e) {
      e.printStackTrace();
    }
  }
xls内容
![image](https://user-images.githubusercontent.com/22414400/102477721-aeb0e500-4097-11eb-9733-9802e2d31f2e.png)

**Comment by wangguanquan** [comment]
把文件发我一份吧，发到我邮箱 guanquan.wang@yandex.com

**Comment by wangguanquan** [comment]
看起来像是一个兼容性问题

**Comment by bob798** [comment]
文件已发邮件，多谢啦。

**Comment by wangguanquan** [comment]
上传了一个SNAPSHOT版本`0.4.10-SNAPSHOT`，请将eec和eec-e3-support升级到此版本试用。

如果拉不到jar包请将下面代码添加到工程pom.xml文件中
```
	<repositories>
		<repository>
			<id>nexus</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
			<releases>
				<enabled>true</enabled>
				<updatePolicy>always</updatePolicy>
			</releases>
			<snapshots>
				<enabled>true</enabled>
				<updatePolicy>always</updatePolicy>
			</snapshots>
		</repository>
	</repositories>
```

**Comment by wangguanquan** [comment]
升级到[v0.4.10](https://github.com/wangguanquan/eec/releases/tag/v0.4.10)修复此问题

**Comment by wangguanquan** [comment]
eec-e3-support升级到v0.4.11，该版本对平台兼容性做了升级
