### ISSUE TITLE
Number(Mac)转xls格式后读取抛异常

### ISSUE THREAD

**Issue by wangguanquan** [wangguanquan/eec#156]
异常信息:
```
Caused by: java.lang.RuntimeException: Miss the Workbook BOF.
	at org.ttzero.excel.entity.e3.GlobalsSubStream.get(GlobalsSubStream.java:49)
	at org.ttzero.excel.reader.BIFF8Reader.parseGlobalSetting(BIFF8Reader.java:539)
	at org.ttzero.excel.reader.BIFF8Reader.parseDocSummaryInformation(BIFF8Reader.java:521)
	at org.ttzero.excel.reader.BIFF8Reader.init(BIFF8Reader.java:140)
	at org.ttzero.excel.reader.BIFF8Reader.<init>(BIFF8Reader.java:90)
	... 30 more

```

**Comment by wangguanquan** [comment]
v0.4.11 提高了其它平台的兼容性
