### ISSUE TITLE
单元格长度限制

### ISSUE THREAD

**Issue by huangguangping** [wangguanquan/eec#161]
当单元格里的字符串长度超过2048时，报堆内存不足错误
java.nio.BufferOverflowException
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:189)
	at java.nio.ByteBuffer.put(ByteBuffer.java:859)
	at org.ttzero.excel.entity.SharedStringTable.push(SharedStringTable.java:145)
	at org.ttzero.excel.entity.SharedStrings.add(SharedStrings.java:216)
	at org.ttzero.excel.entity.SharedStrings.get(SharedStrings.java:182)

**Comment by wangguanquan** [comment]
是`xls`格式的吗？`xlsx`格式并没有复现这个问题，

你可以将测试文件邮件(guanquan.wang@yandex.com)或者微信(254415680)发我吗？

**Comment by wangguanquan** [comment]
我将SharedStringTable缓冲区大小设置为2048，并且没有进行扩容处理，所以出来这个BUG。
这是个很好的问题，感谢你的反馈！
