### ISSUE TITLE
For input string: "true"

### ISSUE THREAD

**Issue by a444878151** [wangguanquan/eec#245]
Exception in thread "main" java.lang.NumberFormatException: For input string: "true"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.ttzero.excel.entity.style.Styles.load(Styles.java:277)
	at org.ttzero.excel.reader.ExcelReader.init(ExcelReader.java:561)
	at org.ttzero.excel.reader.ExcelReader.<init>(ExcelReader.java:499)
	at org.ttzero.excel.reader.ExcelReader.read(ExcelReader.java:640)
	at org.ttzero.excel.reader.ExcelReader.read(ExcelReader.java:247)
	at org.ttzero.excel.reader.ExcelReader.read(ExcelReader.java:160)

applyNumberFormat不仅会返回数字还会返回"true"值

**Comment by wangguanquan** [comment]
EEC的format使用单元格样式，true和false使用的是Office原生格式，如果是字符串转boolean类型可以在定义一个string的setter方法然后boolean.valueOf转换

发自我的 iPhone

**Comment by wangguanquan** [comment]
能否将测试文件和测试代码发我一份

发自我的 iPhone

**Comment by wangguanquan** [comment]
这应该是一个兼容问题，不同工具写出的excel不完全一样，除了这里感觉还有其它地方有类似的问题，所以需要一份测试文件。当然你可以提供更多的信息，比如excel文件是由什么软件所写，版本是多少等信息。

**Comment by a444878151** [comment]
我这边也是收集到的excel。可否给个私人联系方式，私发你文件。

**Comment by wangguanquan** [comment]
点我头像左侧可以看到公开的邮箱，发我的文件之前将内容删除，填写ABC，只要保留原文件格式即可

发自我的 iPhone

**Comment by a444878151** [comment]
这个文件  不能被编辑  编辑后  原格式就失效了

**Comment by wangguanquan** [comment]
好吧。。。你可以fork本项目，然后修改问题代码，本地测试下是否解决。

将Styles第277行代码改为

```
if (isNotEmpty(applyNumberFormat) && ("true".equalsIgnoreCase(applyNumberFormat) || applyNumberFormat.length() == 1 && applyNumberFormat.charAt(0) - '0' == 1))
```

修改后使用`mvn install`本地打包，pom.xml引用使用最新`0.5.1-SNAPSHOT`进行测试

如果解决了可以提交一个pull request，我会将它合并到master分支
