### ISSUE TITLE
The file format is incorrect or corrupted. [/xl/cellimages.xml]

### ISSUE THREAD

**Issue by a444878151** [wangguanquan/eec#247]
Exception in thread "main" org.ttzero.excel.reader.ExcelReadException: The file format is incorrect or corrupted. [/xl/cellimages.xml]
	at org.ttzero.excel.reader.ExcelReader.checkContentType(ExcelReader.java:464)
	at org.ttzero.excel.reader.ExcelReader.init(ExcelReader.java:510)
	at org.ttzero.excel.reader.ExcelReader.<init>(ExcelReader.java:499)
	at org.ttzero.excel.reader.ExcelReader.read(ExcelReader.java:640)
	at org.ttzero.excel.reader.ExcelReader.read(ExcelReader.java:247)
	at org.ttzero.excel.reader.ExcelReader.read(ExcelReader.java:160)

![image](https://user-images.githubusercontent.com/13514068/174757893-9733a240-5543-415b-8090-7490897b9543.png)
报错代码,原始excel稍后通过邮件发你。

遇到此类问题的开发者可以尝试把单元格设置为文本格式解决。

**Comment by wangguanquan** [comment]
应该是第三方工具写Excel文件未按Office OpenXML标准执行，[Content-Types.xml]中有定义`/xl/cellimages.xml`，但是实际却不存在该文件。

对于这种情况可以考虑放宽检查，仅检查必要的文件即可。**最好能将测试文件发我一份，我会进去全面检查做兼容处理。**

**Comment by wangguanquan** [comment]
当然，更欢迎提pull request

**Comment by wangguanquan** [comment]
我看过测试文件，该文件是由Kingsoft Office创建，目前发现两个需要特殊处理的地方

一是本issue反馈的[Content-Types.xml]中有定义/xl/cellimages.xml，但是实际的Excel包中不存在，这个可以放宽检查。
二是worksheet中row的起始下标和结束下标一致，使得无法读取到单元格的值。

暂时可以自定义一个ExcelReader兼容处理，下面是测试代码

```
public static class KingsoftOfficeExcelReader extends ExcelReader {

    public KingsoftOfficeExcelReader(Path path) throws IOException {
        super(path);
    }

    // 这里定义一些必须要检查的属性
    public static final Set<String> MUST_CHECK_PART = new HashSet<>(Arrays.asList(Const.ContentType.WORKBOOK
            , Const.ContentType.SHAREDSTRING, Const.ContentType.SHEET , Const.ContentType.STYLE));

    @Override
    protected ContentType checkContentType(Path root) {
        SAXReader reader = new SAXReader();
        Document document;
        // Read [Content_Types].xml
        try {
            document = reader.read(Files.newInputStream(root.resolve("[Content_Types].xml")));
        } catch (DocumentException | IOException e) {
            FileUtil.rm_rf(root.toFile(), true);
            throw new ExcelReadException("The file format is incorrect or corrupted. [[Content_Types].xml]");
        }
        ContentType contentType = new ContentType();
        List<Element> list = document.getRootElement().elements();
        for (Element e : list) {
            if ("Override".equals(e.getName())) {
                ContentType.Override override = new ContentType.Override(e.attributeValue("ContentType"), e.attributeValue("PartName"));
                if (!Files.exists(root.resolve(override.getPartName().substring(1)))) {
                    if (MUST_CHECK_PART.contains(override.getContentType())) {
                        FileUtil.rm_rf(root.toFile(), true);
                        throw new ExcelReadException("The file format is incorrect or corrupted. [" + override.getPartName() + "]");
                    } else {
                        // 不严格检查的配置仅打印warn信息即可 
                        LOGGER.warn("{} is configured in [Content_Types].xml, but the file is missing.", override.getKey());
                    }
                }
                contentType.add(override);
            }
        }
        return contentType;
    }

    @Override
    protected Sheet sheetFactory(int option) {
        return new XMLSheet() {
            @Override
            public XMLRow createRow() {
                return new XMLRow() {
                    @Override
                    protected int searchSpan() {
                        int span = super.searchSpan();
                        // 兼容处理 spans="x:x" 起始下标和结束下标相同的情况
                        if (fc + 1 == lc) {
                            fc = 0;
                        }
                        return span;
                    }
                };
            }
        };
    }
}
```

**Comment by wangguanquan** [comment]
v0.5.1 release
