### ISSUE TITLE
获取文档字体信息时数字转换异常

### ISSUE THREAD

**Issue by linmii** [wangguanquan/eec#332]
从对接公司获取的excel文档，读取字体信息时报错，fontSize的值是11.0，而Font中size属性为int类型。
已提交PR

```
17:57:07.109 [main] WARN org.ttzero.excel.reader.ExcelReader - Parse style failed.
java.lang.NumberFormatException: For input string: "11.0"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at org.ttzero.excel.entity.style.Font.parseFontTag(Font.java:376)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.ttzero.excel.entity.style.Font.domToFont(Font.java:368)
	at org.ttzero.excel.entity.style.Styles.load(Styles.java:230)
	at org.ttzero.excel.reader.ExcelReader.init(ExcelReader.java:574)
	at org.ttzero.excel.reader.ExcelReader.<init>(ExcelReader.java:512)
	at org.ttzero.excel.reader.ExcelReader.read(ExcelReader.java:663)
	at org.ttzero.excel.reader.ExcelReader.read(ExcelReader.java:233)
	at org.ttzero.excel.reader.ExcelReader.read(ExcelReader.java:155)
```
[2023-02-04_28010.xlsx](https://github.com/wangguanquan/eec/files/10695951/2023-02-04_28010.xlsx)

**Comment by wangguanquan** [comment]
已修复问题，拉取最新fix#312分支本地编译即可

**Comment by wangguanquan** [comment]
没有制定什么特别的发版计划，一般看空闲时间，下个版本大概月中发吧

**Comment by wangguanquan** [comment]
PR  #331

**Comment by wangguanquan** [comment]
v0.5.7 已推

**Comment by linmii** [comment]
> v0.5.7 已推

收到邮件了，哈哈👍👍👍
