### ISSUE TITLE
编译通过了，但是执行总是" No SLF4J providers were found"

### ISSUE THREAD

**Issue by lingbl** [wangguanquan/eec#357]
编译 javac.exe  test.java 没问题，但是执行java.exe test就是错： 
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.

Exception in thread "main" java.lang.NoClassDefFoundError: org/ttzero/excel/util/ExtXMLWriter
        at org.ttzero.excel.reader.ExcelReader.read(ExcelReader.java:654)
        at org.ttzero.excel.reader.ExcelReader.read(ExcelReader.java:233)
        at org.ttzero.excel.reader.ExcelReader.read(ExcelReader.java:155)
        at test.testRead(test.java:17)
        at test.main(test.java:10)
Caused by: java.lang.ClassNotFoundException: org.ttzero.excel.util.ExtXMLWriter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 5 more

//代码test.java:

import org.ttzero.excel.reader.*;
import org.ttzero.excel.reader.XMLSheet;
import java.nio.file.Paths;
import java.io.IOException;

public class test {
    public static void main(String[] args) {
        testRead();
        System.out.println("Hello World");
    }
    

public static void testRead() {
    try {    
        ExcelReader reader = ExcelReader.read(Paths.get("test.xlsx"));
    }
    catch (IOException e) {
        e.printStackTrace();
    }
}
    
}

**Comment by wangguanquan** [comment]
EEC依赖dom4j和slf4j，命令行运行的时候Windows请指定 `-cp .;./lib/slf4j-api-1.7.32.jar;./lib/dom4j-2.1.3.jar;./lib/eec-0.5.9.jar`，linux请指定 `-cp .:./lib/slf4j-api-1.7.32.jar:./lib/dom4j-2.1.3.jar:./lib/eec-0.5.9.jar`

testReader方法内容替换
```
try (ExcelReader reader = ExcelReader.read(Paths.get("test.xlsx"))) {
    reader.sheet(0).rows().forEach(System.out::println);
} catch (IOException e) {
    e.printStackTrace();
}
```

![terminal line](https://github.com/wangguanquan/eec/assets/16704088/4ae71c20-1018-43aa-8038-140f45c21bfd)

**Comment by wangguanquan** [comment]
另外`No SLF4J providers were found`这个异常没有关系，slf4j是日志门面层，日志采集层需要引入log4j或者logback，否则就会提示这个异常，它不影响程序正常执行只是无法输出日志

**Comment by wangguanquan** [comment]
相比使用javac和java命令行，使用jshell更方便所见即可得

> jshell --class-path .:./lib/slf4j-api-1.7.32.jar:./lib/dom4j-2.1.3.jar:./lib/logback-classic-1.2.3.jar:./lib/logback-core-1.2.3.jar:./lib/eec-0.5.9.jar
> import org.ttzero.excel.reader.ExcelReader
> ExcelReader.read(Paths.get("./test.xlsx")).sheet(0).rows().forEach(System.out::println)

![jshell line](https://github.com/wangguanquan/eec/assets/16704088/8bbe7fb4-a5ae-49b4-ba72-acd7989018dd)

**Comment by lingbl** [comment]
谢谢热心回答
